// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxEYlBjDGgOREa4aOwD9_aA0WDT7J6l8',
    appId: '1:106649070093:web:8921ea68d9e70c7bccc344',
    messagingSenderId: '106649070093',
    projectId: 'hackingtool-5c3d0',
    authDomain: 'hackingtool-5c3d0.firebaseapp.com',
    storageBucket: 'hackingtool-5c3d0.firebasestorage.app',
    measurementId: 'G-1269F90Z6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJcDiB4tmeQpR0J3qZGF-tLQQ0MECw-6Y',
    appId: '1:106649070093:android:a96361ab1cc3d390ccc344',
    messagingSenderId: '106649070093',
    projectId: 'hackingtool-5c3d0',
    storageBucket: 'hackingtool-5c3d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5z0VMpqG7wYE9Xd6_vtSUvsfOF2GXcA',
    appId: '1:106649070093:ios:cc63a0b2fd1e6ab4ccc344',
    messagingSenderId: '106649070093',
    projectId: 'hackingtool-5c3d0',
    storageBucket: 'hackingtool-5c3d0.firebasestorage.app',
    iosBundleId: 'com.example.jammingTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5z0VMpqG7wYE9Xd6_vtSUvsfOF2GXcA',
    appId: '1:106649070093:ios:cc63a0b2fd1e6ab4ccc344',
    messagingSenderId: '106649070093',
    projectId: 'hackingtool-5c3d0',
    storageBucket: 'hackingtool-5c3d0.firebasestorage.app',
    iosBundleId: 'com.example.jammingTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxEYlBjDGgOREa4aOwD9_aA0WDT7J6l8',
    appId: '1:106649070093:web:20712f1c4833925dccc344',
    messagingSenderId: '106649070093',
    projectId: 'hackingtool-5c3d0',
    authDomain: 'hackingtool-5c3d0.firebaseapp.com',
    storageBucket: 'hackingtool-5c3d0.firebasestorage.app',
    measurementId: 'G-2EVY946TKS',
  );

}